blank_issues_enabled: false
contact_links:
  - name: Web sitesi / Website
    url: https://muhammetburakakkas.com
    about: Proje sahibi ve iletişim bilgileri / Project owner and contact information.
