name: Feature request (English)
description: Suggest a new feature or improvement.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - All platforms
        - Linux
        - Android
        - Windows
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true
